#ifndef __Definitions_H__
#define __Definitions_H__
#define DISPLAY_TIME_SPLASH_SCENE 1
#define TRANSITION_TIME 1.0
#define OBJECT_SPAWN_FREQUENCY 0.005
#define OBSTICAL_COLLISION_BITMASK 0x000001
#define MONSTER_COLLISION_BITMASK 0X000002
#define POINT_COLLISION_BITMASK 0x000003
#define SCORE_FONT_SIZE 0.1
#define LIVES_FONT_SIZE 0.1

#endif // __Definitions_H__
